name = "tactics_generation"
version = "0.1.0"
defaultTargets = ["tactics_generation"]

[[lean_exe]]
name = "tactics_generation"
root = "Main"

[[require]]
name = "batteries"
scope = "leanprover-community"

[[require]]
name = "Qq"
scope = "leanprover-community"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"